/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _codehandleronly_h_
#define _codehandleronly_h_
//---------------------------------------------------------------------------------
extern const unsigned char codehandleronly[];
extern const int codehandleronly_size;
//---------------------------------------------------------------------------------
#endif //_codehandleronly_h_
//---------------------------------------------------------------------------------
